### ISSUE TITLE
Notebooks not working

### ISSUE THREAD

**Issue by StefanoBuccelli** [alejoe91/MEArec#53]
Ciao! It looks like a great work from the preprint. I'm trying to start from the notebook: generate_templates_and_recordings

**First error** in the first cell: 

>   File "c:\users\buccellilab\documents\github\mearec\MEArec\generators\templategenerator.py", line 190
>     raise FileNotFoundError(f'{tmp_folder} not found. Something went wrong in the template generation phase.')
>                                                                                                             ^
> SyntaxError: invalid syntax

I removed that f and it works :)

**Second error:**

> AttributeError                            Traceback (most recent call last)
> <ipython-input-4-2076b4d78a9b> in <module>
>       1 # define cell_models folder
>       2 cell_folder = default_info['cell_models_folder']
> ----> 3 template_params = mr.get_default_template_params()
>       4 pprint(template_params)

AttributeError: module 'MEArec' has no attribute 'get_default_template_params'

You probably forgot one s. the name is: 
template_params = mr.get_default_template**s**_params()

Then, it rises **another error.**

> Simulation time:  11.641000032424927 
> 
> 
> 
> ---------------------------------------------------------------------------
> FileNotFoundError                         Traceback (most recent call last)
> <ipython-input-6-d051667b4c24> in <module>
>       2 template_params['probe'] = 'tetrode-mea-l'
>       3 # the templates are not saved, but the intracellular simulations are saved in 'templates_folder'
> ----> 4 tempgen = mr.gen_templates(cell_models_folder=cell_folder, params=template_params)
>       5 # this will take a few minutes...
> 
> c:\users\buccellilab\documents\github\mearec\MEArec\generation_tools.py in gen_templates(cell_models_folder, params, templates_tmp_folder, intraonly, parallel, delete_tmp, verbose)
>     196                                 delete_tmp=delete_tmp,
>     197                                 verbose=verbose)
> --> 198     tempgen.generate_templates()
>     199 
>     200     return tempgen
> 
> c:\users\buccellilab\documents\github\mearec\MEArec\generators\templategenerator.py in generate_templates(self)
>     188 
>     189         if not Path(tmp_folder).is_dir():
> --> 190             raise FileNotFoundError('{tmp_folder} not found. Something went wrong in the template generation phase.')
>     191 
>     192         templates, locations, rotations, celltypes = load_tmp_eap(tmp_folder)
> 
> FileNotFoundError: {tmp_folder} not found. Something went wrong in the template generation phase.

it looks like it is not able to find the right folder. Can you clarify this point? Should I set the folder path somewhere?

Thanks a lot!!
Stefano

**Comment by StefanoBuccelli** [comment]
I also tried like this:

> if __name__ == '__main__':
>     tempgen = mr.gen_templates(cell_models_folder=cell_folder, params=template_params,templates_tmp_folder=None, intraonly=False, parallel=True, delete_tmp=True)

given that I'm working with Windows.. but no success so far..

Thanks!

**Comment by alejoe91** [comment]
Hi @StefanoBuccelli 

The notebook is a bit outdated :) I'll update soon!

> Ciao! It looks like a great work from the preprint. I'm trying to start from the notebook: generate_templates_and_recordings
> 
> **First error** in the first cell:
> 
> > File "c:\users\buccellilab\documents\github\mearec\MEArec\generators\templategenerator.py", line 190
> > raise FileNotFoundError(f'{tmp_folder} not found. Something went wrong in the template generation phase.')
> > ^
> > SyntaxError: invalid syntax
> 
> I removed that f and it works :)


The `f` strings whould work with Python >= 3.6. It makes life much easier, so I recommend updating it.

 

> **Second error:**
> 
> > AttributeError                            Traceback (most recent call last)
> >  in 
> > 1 # define cell_models folder
> > 2 cell_folder = default_info['cell_models_folder']
> > ----> 3 template_params = mr.get_default_template_params()
> > 4 pprint(template_params)
> 
> AttributeError: module 'MEArec' has no attribute 'get_default_template_params'
> 
> You probably forgot one s. the name is:
> template_params = mr.get_default_template**s**_params()


Probably :)

> Then, it rises **another error.**
> 
> > Simulation time:  11.641000032424927
> > 
> > FileNotFoundError                         Traceback (most recent call last)
> >  in 
> > 2 template_params['probe'] = 'tetrode-mea-l'
> > 3 # the templates are not saved, but the intracellular simulations are saved in 'templates_folder'
> > ----> 4 tempgen = mr.gen_templates(cell_models_folder=cell_folder, params=template_params)
> > 5 # this will take a few minutes...
> > c:\users\buccellilab\documents\github\mearec\MEArec\generation_tools.py in gen_templates(cell_models_folder, params, templates_tmp_folder, intraonly, parallel, delete_tmp, verbose)
> > 196                                 delete_tmp=delete_tmp,
> > 197                                 verbose=verbose)
> > --> 198     tempgen.generate_templates()
> > 199
> > 200     return tempgen
> > c:\users\buccellilab\documents\github\mearec\MEArec\generators\templategenerator.py in generate_templates(self)
> > 188
> > 189         if not Path(tmp_folder).is_dir():
> > --> 190             raise FileNotFoundError('{tmp_folder} not found. Something went wrong in the template generation phase.')
> > 191
> > 192         templates, locations, rotations, celltypes = load_tmp_eap(tmp_folder)
> > FileNotFoundError: {tmp_folder} not found. Something went wrong in the template generation phase.
> 
> it looks like it is not able to find the right folder. Can you clarify this point? Should I set the folder path somewhere?

As I said, the notebook is not updated.. The actual argument should be `templates_tmp_folder` (https://github.com/alejoe91/MEArec/blob/master/MEArec/generation_tools.py#L148-L149)
> 
> Thanks a lot!!
> Stefano

I'll try to update the notebook over the weekend. Thanks for spotting the errors!

Alessio

**Comment by alejoe91** [comment]
> I also tried like this:
> 
> > if **name** == '**main**':
> > tempgen = mr.gen_templates(cell_models_folder=cell_folder, params=template_params,templates_tmp_folder=None, intraonly=False, parallel=True, delete_tmp=True)
> 
> given that I'm working on Windows.. but no success so far..
> 
> Thanks!

This should work if the first one is solved :)

**Comment by StefanoBuccelli** [comment]
Awesome! Thanks a lot!!
It's time to update my python :)

**Comment by alejoe91** [comment]
@StefanoBuccelli can you try this PR? https://github.com/alejoe91/MEArec/pull/54

**Comment by StefanoBuccelli** [comment]
Hi! Thanks a lot.
Probably is my fault, somehow, but here is the error I'm getting.




> Simulation time:  14.731472969055176 
> 
> 
> 
> ---------------------------------------------------------------------------
> FileNotFoundError                         Traceback (most recent call last)
> <ipython-input-7-066afbe4ec58> in <module>
>       2 template_params['probe'] = 'Neuronexus-32'
>       3 # the templates are not saved, but the intracellular simulations are saved in 'templates_folder'
> ----> 4 tempgen = mr.gen_templates(cell_models_folder=cell_folder, params=template_params)
>       5 # this will take a few minutes...
> 
> c:\users\sbuccelli\appdata\local\programs\python\python37\lib\site-packages\MEArec\generation_tools.py in gen_templates(cell_models_folder, params, templates_tmp_folder, intraonly, parallel, delete_tmp, verbose)
>     196                                 delete_tmp=delete_tmp,
>     197                                 verbose=verbose)
> --> 198     tempgen.generate_templates()
>     199 
>     200     return tempgen
> 
> c:\users\sbuccelli\appdata\local\programs\python\python37\lib\site-packages\MEArec\generators\templategenerator.py in generate_templates(self)
>     188 
>     189         if not Path(tmp_folder).is_dir():
> --> 190             raise FileNotFoundError(f'{tmp_folder} not found. Something went wrong in the template generation phase.')
>     191 
>     192         templates, locations, rotations, celltypes = load_tmp_eap(tmp_folder)
> 
> FileNotFoundError: C:\Users\sbuccelli\Documents\GitHub\MEArec\notebooks\physrot\tmp_10_Neuronexus-32 not found. Something went wrong in the template generation phase.


I don't know whether it is related or not but I'm getting errors all day with neuron (neuron.test() failed because of multiprocessing issues even though I have MPI installed) and I can't install LFPy properly on one machine (it tells me, I don't have Visual C++ 14.0 build tools that I just installed). I will try again, probably on Monday.
Thanks a lot anyway!!

**Comment by alejoe91** [comment]
You can also try to install LFPy through anaconda! See [this](https://github.com/alejoe91/MEArec/issues/51#issuecomment-553575175)

Can you also try to run the `gen_templates` with the `verbose=True` option? You should get logs in the terminal attached to the notebook.

Let me know if that fixes it, otherwise we'll find another solution.

**Comment by StefanoBuccelli** [comment]
Ok, thanks!
Now I managed to install LFPy correctly, not sure neuron is set up correctly given the error that shows when I run: neuron.test()
![image](https://user-images.githubusercontent.com/26065664/70423158-40414c00-1a6d-11ea-9379-cd960e176958.png)

Anyway, these are the logs in terminal attached to the nobook (when I run the gen_templates with verbose true) before the fatal error that I'm getting (probably a pointer to a non existent location).
![image](https://user-images.githubusercontent.com/26065664/70423057-1425cb00-1a6d-11ea-866a-25266e3d41ff.png)

My guess is that is somehow related to the MPI, multiprocessing stuff (that indeed is related to the error with neuron.test(). TypeError: cannot serialize '_io.TextIOWrapper' object

So, mearec probably works as expected, the problem is realated to neuron. make sense to you?
Thanks

**Comment by alejoe91** [comment]
Yes, indeed it seems that the NEURON mechanisms were not compiled at all. You can probably find some info on how to solve this NEURON problem on their forum! I think that when this is solved MEArec should run smoothly :)

**Comment by StefanoBuccelli** [comment]
Ok, I will check better on their forum. I guess it is somehow related to cygwin.. 
Thanks again for your support, I will let you know :)

**Comment by StefanoBuccelli** [comment]
Ok, I managed to install both Neuron and LFPy on a mac. 
Still some problems:
here is the output of the cell:

> Compiling NEURON models
> Starting  1
> Starting  2
> 
> 
> 
> 
>  L5_DBC_bAC217_1 1 / 13 
> 
> Starting  3
> 
>  L5_BTC_bAC217_1 2 / 13 
> 
> 
> 
> Starting  4
>  L5_MC_bAC217_1 3 / 13 
> 
> 
> Starting  5
> 
> 
> 
>  L5_TTPC1_cADpyr232_1 4 / 13 
> 
> 
> 
> Starting  6
> Starting  7
> Starting  8
>  L5_LBC_bAC217_1 5 / 13 
> 
> 
> 
> 
> 
> 
> 
> 
>  L5_ChC_cACint209_1 8 / 13 
> 
>  L5_TTPC2_cADpyr232_1 7 / 13 
> 
> 
> 
>  L5_NGC_bNAC219_1 6 / 13 
> 
> 
> Starting  9
> 
> 
> 
>  L5_NBC_bAC217_1 9 / 13 
> 
> 
> Starting  10
> 
> 
>  L5_STPC_cADpyr232_1 10 / 13 
> 
> 
> Starting  11
> 
> 
>  L5_UTPC_cADpyr232_1 11 / 13 
> 
> 
> Starting  12
> 
> 
>  L5_SBC_bNAC219_1 12 / 13 
> 
> 
> Starting  13
> 
> 
>  L5_BP_bAC217_1 13 / 13 
> 
> 
> Exiting  9
> Exiting  10
> Exiting  5
> Exiting  8
> Exiting  1
> Exiting  6
> Exiting  12
> Exiting  13
> Exiting  3
> Exiting  7
> Exiting  4
> Exiting  11
> Exiting  2
> 
> 
> 
> Simulation time:  1.637213945388794 
> 
> 
> 
> ---------------------------------------------------------------------------
> FileNotFoundError                         Traceback (most recent call last)
> <ipython-input-5-c2bb9b9b6e73> in <module>
>       2 template_params['probe'] = 'Neuronexus-32'
>       3 # the templates are not saved, but the intracellular simulations are saved in 'templates_folder'
> ----> 4 tempgen = mr.gen_templates(cell_models_folder=cell_folder, params=template_params, verbose=True)
>       5 # this will take a few minutes...
> 
> ~/Documents/GitHub/MEArec/MEArec/generation_tools.py in gen_templates(cell_models_folder, params, templates_tmp_folder, intraonly, parallel, delete_tmp, verbose)
>     196                                 delete_tmp=delete_tmp,
>     197                                 verbose=verbose)
> --> 198     tempgen.generate_templates()
>     199 
>     200     return tempgen
> 
> ~/Documents/GitHub/MEArec/MEArec/generators/templategenerator.py in generate_templates(self)
>     188 
>     189         if not Path(tmp_folder).is_dir():
> --> 190             raise FileNotFoundError(f'{tmp_folder} not found. Something went wrong in the template generation phase.')
>     191 
>     192         templates, locations, rotations, celltypes = load_tmp_eap(tmp_folder)
> 
> FileNotFoundError: /Users/stefanobuccelli/Documents/GitHub/MEArec/notebooks/physrot/tmp_10_Neuronexus-32 not found. Something went wrong in the template generation phase.

indeed that folder does not exist..

here is the log of verbose:

> [I 10:44:25.817 NotebookApp] Kernel started: f32a27b3-c126-4bee-ab6b-4e098dd58752
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>     import MEAutility as mu
> ImportError: No module named MEAutility
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>     import MEAutility as mu
> ImportError: No module named MEAutility
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>     import MEAutility as mu
> ImportError: No module named MEAutility
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>     import MEAutility as mu
> ImportError: No module named MEAutility
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>     import MEAutility as mu
> ImportError: No module named MEAutility
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>     import MEAutility as mu
> ImportError: No module named MEAutility
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>     import MEAutility as mu
> ImportError: No module named MEAutility
> Traceback (most recent call last):
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>     import MEAutility as mu
> ImportError: No module named MEAutility
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>     import MEAutility as mu
> ImportError: No module named MEAutility
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>     import MEAutility as mu
> ImportError: No module named MEAutility
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>     import MEAutility as mu
> ImportError: No module named MEAutility
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>     import MEAutility as mu
> ImportError: No module named MEAutility
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>     import MEAutility as mu
> ImportError: No module named MEAutility
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>     import MEAutility as mu
> ImportError: No module named MEAutility
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>     import MEAutility as mu
> ImportError: No module named MEAutility
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>     import MEAutility as mu
> ImportError: No module named MEAutility
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>     import MEAutility as mu
> ImportError: No module named MEAutility
> Traceback (most recent call last):
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>     import MEAutility as mu
> ImportError: No module named MEAutility
>     import MEAutility as mu
> ImportError: No module named MEAutility
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>     import MEAutility as mu
> ImportError: NoTraceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
> Traceback (most recent call last):
>     import MEAutility as mu
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
> ImportError: No module named MEAutility
>     import MEAutility as mu
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
> ImportError: No module named MEAutility
>     import MEAutility as mu
> ImportError: No module named MEAutility
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>     import MEAutility as mu
> ImportError: No module named MEAutility
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>     import MEAutility as mu
> ImportError: No module named MEAutility
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>  module named MEAutility
>     import MEAutility as mu
> ImportError: No module named MEAutility
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>     import MEAutility as mu
> ImportError: No module named MEAutility
> Traceback (most recent call last):
>   File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
>     import MEAutility as mu
> ImportError: No module named MEAutility
> [I 10:46:25.766 NotebookApp] Saving file at /Documents/GitHub/MEArec/notebooks/generate_templates_and_recordings.ipynb

I can't figure out why it is not able to import MEAutility... It has it and it imports it normally every time but not there..

Any idea? thanks

**Comment by alejoe91** [comment]
HI @StefanoBuccelli 

Are you running it from a notebook using conda? you might need to run: `conda install nb_conda` to use a conda environment in the notebook.

Can you test if the CLI works? Try to run, from the terminal (in the MEArec env), this code:

`>>> mearec gen-templates -prb Neuronexus-32 -n 20 -v`

This is the same as the Python script :) If that works, then it is indeed an environment problem.

**Comment by StefanoBuccelli** [comment]
Nope, I'm not using conda.. I'm running from bash

**Comment by alejoe91** [comment]
what's the output of `pip list`? What python version are you using?

**Comment by StefanoBuccelli** [comment]
airdistefano2:~ stefanobuccelli$ pip3 list
Package            Version Location                                      
------------------ ------- ----------------------------------------------
appnope            0.1.0   
attrs              19.3.0  
backcall           0.1.0   
bleach             3.1.0   
Click              7.0     
cycler             0.10.0  
Cython             0.29.14 
decorator          4.4.1   
defusedxml         0.6.0   
elephant           0.6.4   
entrypoints        0.3     
h5py               2.10.0  
importlib-metadata 1.2.0   
ipykernel          5.1.3   
ipython            7.10.1  
ipython-genutils   0.2.0   
ipywidgets         7.5.1   
jedi               0.15.1  
Jinja2             2.10.3  
jsonschema         3.2.0   
jupyter            1.0.0   
jupyter-client     5.3.4   
jupyter-console    6.0.0   
jupyter-core       4.6.1   
kiwisolver         1.1.0   
MarkupSafe         1.1.1   
matplotlib         3.1.2   
MEArec             1.3.7   /Users/stefanobuccelli/Documents/GitHub/MEArec
MEAutility         1.3.3   
mistune            0.8.4   
more-itertools     8.0.2   
mpi4py             3.0.3   
nbconvert          5.6.1   
nbformat           4.4.0   
neo                0.8.0   
NEURON             7.7     
notebook           6.0.2   
numpy              1.17.4  
pandocfilters      1.4.2   
parso              0.5.1   
pexpect            4.7.0   
pickleshare        0.7.5   
pip                19.0.3  
prometheus-client  0.7.1   
prompt-toolkit     2.0.10  
ptyprocess         0.6.0   
Pygments           2.5.2   
pyparsing          2.4.5   
pyrsistent         0.15.6  
python-dateutil    2.8.1   
PyYAML             5.2     
pyzmq              18.1.1  
qtconsole          4.6.0   
quantities         0.12.3  
scipy              1.3.3   
Send2Trash         1.5.0   
setuptools         40.8.0  
six                1.13.0  
terminado          0.8.3   
testpath           0.4.4   
tornado            6.0.3   
tqdm               4.40.2  
traitlets          4.3.3   
wcwidth            0.1.7   
webencodings       0.5.1   
widgetsnbextension 3.5.1   
zipp               0.6.0

**Comment by StefanoBuccelli** [comment]
Python 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)] on darwin

**Comment by alejoe91** [comment]
ok that looks good. Have you tried the command line approach?

**Comment by StefanoBuccelli** [comment]
sorry, probably I'm not familiar with the command line approach, here's what I tried:
>>> import MEArec as mr
>>> mr gen-templates -prb Neuronexus-32 -n 20 -v
  File "<stdin>", line 1
    mr gen-templates -prb Neuronexus-32 -n 20 -v
         ^
SyntaxError: invalid syntax
>>> mr gen_templates -prb Neuronexus-32 -n 20 -v
  File "<stdin>", line 1
    mr gen_templates -prb Neuronexus-32 -n 20 -v
                   ^
SyntaxError: invalid syntax

**Comment by alejoe91** [comment]
No worries.
You don't have to write a script. 
From the terminal, just run:

`mearec gen-templates -prb Neuronexus-32 -n 20 -v`

(same way that you ran `pip3 list`)

**Comment by StefanoBuccelli** [comment]
ops!!

airdistefano2:~ stefanobuccelli$ mearec gen-templates -prb Neuronexus-32 -n 20 -v
Compiling NEURON models
Traceback (most recent call last):
  File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
    import MEAutility as mu
ImportError: No module named MEAutility
Starting  1


 L5_DBC_bAC217_1 1 / 13 


Starting  2


 L5_BTC_bAC217_1 2 / 13 


Starting  4
Starting  3


 L5_MC_bAC217_1 3 / 13 




 L5_TTPC1_cADpyr232_1 4 / 13 


Starting  5


 L5_LBC_bAC217_1 5 / 13 


Starting  6


 L5_NGC_bNAC219_1 6 / 13 


Starting  7


 L5_TTPC2_cADpyr232_1 7 / 13 


Starting  8


 L5_ChC_cACint209_1 8 / 13 


Starting  9


 L5_NBC_bAC217_1 9 / 13 


Starting  11


 L5_UTPC_cADpyr232_1 11 / 13 


Starting  10


 L5_STPC_cADpyr232_1 10 / 13 


Starting  12


 L5_SBC_bNAC219_1 12 / 13 


Starting  13


 L5_BP_bAC217_1 13 / 13 


Traceback (most recent call last):
  File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
    import MEAutility as mu
ImportError: No module named MEAutility
Traceback (most recent call last):
  File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
    import MEAutility as mu
ImportError: No module named MEAutility
Traceback (most recent call last):
  File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
    import MEAutility as mu
ImportError: No module named MEAutility
Traceback (most recent call last):
  File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
    import MEAutility as mu
ImportError: No module named MEAutility
Traceback (most recent call last):
  File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
    import MEAutility as mu
ImportError: No module named MEAutility
Traceback (most recent call last):
  File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
    import MEAutility as mu
ImportError: No module named MEAutility
Traceback (most recent call last):
  File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
    import MEAutility as mu
ImportError: No module named MEAutility
Exiting  6
Exiting  4
Traceback (most recent call last):
  File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
    import MEAutility as mu
ImportError: No module named MEAutility
Traceback (most recent call last):
  File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
    import MEAutility as mu
ImportError: No module named MEAutility
Traceback (most recent call last):
  File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
    import MEAutility as mu
ImportError: No module named MEAutility
Traceback (most recent call last):
  File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
    import MEAutility as mu
ImportError: No module named MEAutility
Exiting  9
Traceback (most recent call last):
  File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
    import MEAutility as mu
ImportError: No module named MEAutility
Traceback (most recent call last):
Exiting  2
  File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/simulate_cells.py", line 14, in <module>
    import MEAutility as mu
ImportError: No module named MEAutility
Exiting  5
Exiting  12
Exiting  11
Exiting  1
Exiting  3
Exiting  13
Exiting  7
Exiting  10
Exiting  8



Simulation time:  1.1049540042877197 



Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/mearec", line 11, in <module>
    load_entry_point('MEArec', 'console_scripts', 'mearec')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/cli.py", line 176, in gen_templates
    verbose=verbose)
  File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/generation_tools.py", line 198, in gen_templates
    tempgen.generate_templates()
  File "/Users/stefanobuccelli/Documents/GitHub/MEArec/MEArec/generators/templategenerator.py", line 190, in generate_templates
    raise FileNotFoundError(f'{tmp_folder} not found. Something went wrong in the template generation phase.')
FileNotFoundError: /Users/stefanobuccelli/.config/mearec/templates/physrot/tmp_20_Neuronexus-32 not found. Something went wrong in the template generation phase.

**Comment by alejoe91** [comment]
Can you send me an email? It's easier if we have a chat :)
I think it's not the same python and I recommend using anaconda to make sure about it

**Comment by StefanoBuccelli** [comment]
Sure! Thanks!

**Comment by alejoe91** [comment]
The problem here was that the system `python3` was used and [parts of the template generation](https://github.com/alejoe91/MEArec/blob/master/MEArec/generators/templategenerator.py#L24) invoke `python` as subprocesses. 

The solution is to install a conda or virtualenv environment so that the `python` command points to the right Python.
